### PR TITLE
Feature: keyboard shortcuts for toggles

### PR DESCRIPTION
**Pull request by erikjung**
This adds the ability to use keyboard commands for toggling the state/visibility of notes, labels and code examples.

The chosen commands:

``` js
const LABELS_SHORTCUT = 'ctrl a';
const CODE_SHORTCUT = 'ctrl s';
const NOTES_SHORTCUT = 'ctrl d';
```

Alternative suggestions welcome. [Here](https://github.com/intesso/vkeys/blob/master/vkeys.js) are the available keys.

I used `ctrl` in order to not trigger anything when `<input>`s within materials are interacted with.

---

cc @tylersticka

### CODE REVIEW

**Comment by lyzadanger** [comment]
Is this PR still valid in light of @tylersticka 's considerable changes to structure? Sorry it's been languishing. Ready to think about it now :)

**Comment by erikjung** [comment]
Yes, it should be.

**Comment by lyzadanger** [comment]
My only hesitation is that I think the label show-hide feature is kind of silly. Thoughts? 

Otherwise, totally rock on and :star: for that ES6 module syntax.

**Comment by tylersticka** [comment]
I say "keep it" because it's already in there and it feels weird to remove _one_ Fabricator feature while keeping the others intact.

**Comment by lyzadanger** [comment]
@tylersticka Yeah, can't hurt.

**Pull request merged**
