### PR TITLE
Hooking up external links to actual data

### PR DESCRIPTION
**Pull request by tylersticka**
This takes the previously non-functional "external link" HTML/CSS and wires it up to support actual data.

### CODE REVIEW

**Comment by lyzadanger** [comment]
Hi! This looks good, but does bring up a tangential equation about how we want to maintain documentation for our alterations? Perhaps amend the repo-wide `README`? I'm open to suggestions.

**Comment by tylersticka** [comment]
I think it makes sense to maintain our own README.

**Comment by tylersticka** [comment]
@lyzadanger Is there any action required now for this PR specifically before it can be merged?

**Comment by lyzadanger** [comment]
@tylersticka You choice on whether you want to introduce a new README as part of this PR or after!

**Comment by tylersticka** [comment]
After! I've got at least two other tweaks I'd like to make and then that seems like a good time to write one.

I'll make an issue for it, though!

**Pull request merged**
